//   Copyright 2025 Anthony W. van Leeuwen
//
//   Licensed under the Apache License, Version 2.0 (the "License");
//   you may not use this file except in compliance with the License.
//   You may obtain a copy of the License at
//
//       http://www.apache.org/licenses/LICENSE-2.0
//
//   Unless required by applicable law or agreed to in writing, software
//   distributed under the License is distributed on an "AS IS" BASIS,
//   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//   See the License for the specific language governing permissions and
//   limitations under the License.
//
namespace LoadSQLDatabase
{
    /// <summary>
    ///
    /// </summary>
    /// <autogeneratedoc />
    /// TODO Edit XML Comment Template for CsvColumnDetails
    public class CsvColumnDetails
    {
        private int columnId;
        private string columnName;
        private string columnOrdinalPosition;

        /// <summary>
        /// Initializes a new instance of the <see cref="CsvColumnDetails"/> class.
        /// </summary>
        /// <param name="p_columnId">The p column identifier.</param>
        /// <param name="p_columnName">Name of the p column.</param>
        /// <param name="p_columnOrdinalPosition">The p column ordinal position.</param>
        public CsvColumnDetails(int p_columnId, string p_columnName, string p_columnOrdinalPosition)
        {
            columnId = p_columnId;
            columnName = p_columnName;
            columnOrdinalPosition = p_columnOrdinalPosition;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="CsvColumnDetails"/> class.
        /// </summary>
        public CsvColumnDetails()
        { }

        /// <summary>
        /// Gets or sets the column identifier.
        /// </summary>
        /// <value>
        /// The column identifier.
        /// </value>
        public int ColumnId
        { get { return columnId; } set { columnId = value; } }

        /// <summary>
        /// Gets or sets the name of the column.
        /// </summary>
        /// <value>
        /// The name of the column.
        /// </value>
        public string ColumnName
        { get { return columnName; } set { columnName = value; } }

        /// <summary>
        /// Gets or sets the column ordinal position.
        /// </summary>
        /// <value>
        /// The column ordinal position.
        /// </value>
        public string ColumnOrdinalPosition
        { get { return columnOrdinalPosition; } set { columnOrdinalPosition = value; } }
    }
}